version: '3.6'
networks:
  default:
    external:
      name: ${NETWORK_NAME}
services:
  mysql:
    image: library/percona:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DOCKER_DATA_DIR}/mysql/data/:/var/lib/mysql
      - ${DOCKER_DATA_DIR}/mysql/log/:/var/log/mysql

  nginx:
    build:
      context: ../../
      dockerfile: docker/src/nginx/Dockerfile
    image: jjttnginx
    ports:
      - ${FRONT_END_PORT}:80
    links:
      - backend

  backend:
    build:
      context: ../../
      dockerfile: docker/src/php/Dockerfile
      args:
        PHP_ENV: ${PHP_ENV}
    image: jjttphp
    environment:
      APP_URL: http://${APP_DOMAIN}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USERNAME}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "tbUEyZ1yUOpCPIj1czHi5EzMWCNbjPKU"
      CACHE_DRIVER: "file"
      SESSION_DRIVER: "file"
      DB_HOST: "mysql"
      QUEUE_DRIVER: "sync"
      LOG_CHANNEL: "stderr"
      PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
    links:
      - mysql
    volumes:
      - ../../:/app
